# Generated by Django 5.0.6 on 2024-06-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_profile_picture',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
