version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "configurations.wsgi:application", "--bind", "0.0.0.0:8002"]
    ports:
      - "8002:8002"
    volumes:
      - ./configurations/configurations:/app/configurations
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: lena1818
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
