# Generated by Django 5.0.6 on 2024-06-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_note_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_public',
        ),
    ]
