# Generated by Django 5.0.6 on 2024-06-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_stagenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagenote',
            name='catstage',
        ),
    ]
